### ISSUE TITLE
Direction Input: Behavior and new Ideas

### ISSUE THREAD

**Issue by AnTi-ArT** [mypaint/libmypaint#10]
Just a place to discuss/brainstorm.

Right now the Direction input goes from 0 to 180, ignoring U-turns. With this, elliptic dabs end up smoother on the canvas and it doesn't matter: a 90 rotated ellipse looks exactly like a 270 one anyway.

However, when using the direction input for anything except rotation the results seem somewhat unexpected (if you're not aware that it isn't 360):

![direction](https://cloud.githubusercontent.com/assets/6949092/4072673/e997b4cc-2e89-11e4-839e-92354cfd215c.png)

There are always two "breaks". Now what would an user actually expect from a "Direction" input? A circle that grows from 0 to 360, and the break... If you think logically it makes sense to have the break at the top, clockwise, because _the direction of the stroke_ points towards 0°... But my guts say: The break should be on the right, going counterclockwise, because that's how you learn to think about angles in school

Of course, the rotation for ellipses works [better with 180 and I agree](https://github.com/mypaint/libmypaint/issues/8#issuecomment-53545381) that it doesn't make sense to have two Inputs for direction. Maybe the 360 can be converted to 180 just before dab rotation is calculated/drawn? (I have not looked at the code)... Oh, and I wonder, changing the direction behavior now could "break" old brushes? This should be avoided :|

While thinking about it, I had an idea for a new input: Direction Deviation - How much the direction changes from the start of a stoke. It would go from 0 to 180 (or 0 to 100%?) and could work without negative values, just representing the delta/difference. In that case, there is no -180 to 180 break.

**Comment by briend** [comment]
This code actually is useful for the offset side and mirror calculation as it avoids the jitter issue and makes it easier to adjust the offset angle from 90 to whatever any you want.  I've combined the two which simplified it a bit.

**Comment by briend** [comment]
This has been merged in master.  Yay!
