### ISSUE TITLE
[Documentation] Who uses libmypaint - please consider adding a subsection who may be using libmypaint so far

### ISSUE THREAD

**Issue by ghost** [mypaint/libmypaint#106]
The most recent gimp releases now require libmypaint, so I was curious for that and googling.

Do you think the documentation could very briefly mention who is all using libmypaint so far? For example MyPaint and gimp and two candidates; perhaps there are more. This may also allow users to look for these projects and help them. This could perhaps be a simple subsection on the main readme.

Not sure if this is a good issue request since time my be limited, so please do feel free to close this issue at any moment in time. Thanks!

**Comment by Jehan** [comment]
If I recall, OpenToonz also added support for MyPaint brushes through libmypaint.

As for the topic, I don't think it's a bad idea though I am not the maintainer so @achadwick should decide. If I were you, I'd just propose a pull request editing the bottom of the README file, starting a list with MyPaint, GIMP and OpenToonz. This way, we'll just have to accept it in a click if the maintainer agrees and it will just grow further later when we get aware of more usage.
