### ISSUE TITLE
Cannot run Demo on gentoo-based

### ISSUE THREAD

**Issue by Ygarr** [mypaint/libmypaint#117]
Cannot run Demo on Sabayon. 

```
 pkg-config --list-all | grep -i mypaint
libmypaint                          libmypaint - MyPaint's brushstroke rendering library (1.3.0)
libmypaint-2.0                      libmypaint - MyPaint's brushstroke rendering library (2.0.0-alpha)
libmypaint-gegl                     libmypaint - MyPaint brush engine library, with GEGL integration.
mypaint-brushes-1.0                 mypaint-brushes - Brushes used by MyPaint and other software using libmypaint.
```

then

/mypaint) 
└> 
```
python setup.py demo
Package libmypaint-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libmypaint-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libmypaint-2.0' found
Traceback (most recent call last):
  File "setup.py", line 603, in <module>
    ext_modules=get_ext_modules(),
  File "setup.py", line 512, in get_ext_modules
    extra_compile_args=extra_compile_args,
  File "setup.py", line 451, in pkgconfig
    universal_newlines=True,
  File "/usr/lib64/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['pkg-config', '--libs', 'pygobject-3.0', 'glib-2.0', 'libpng', 'lcms2', 'gtk+-3.0', 'libmypaint-2.0']' returned non-zero exit status 1
```

**Comment by hartwork** [comment]
Where do you have `libmypaint-2.0.pc` installed and what is your `${PKG_CONFIG_PATH}` set to, if any?

**Comment by aoloe** [comment]
i have installed libmypaint in ~/bin/libmypaint ... what should be in `PKG_CONFIG_PATH`?

**Comment by aoloe** [comment]
ok, found:

`export PKG_CONFIG_PATH=~/bin/libmypaint/lib/pkgconfig/`

**Comment by hartwork** [comment]
Looks good. Does it work?

**Comment by UmarSpa** [comment]
I am getting the same error, when I run scons as indicated here: https://github.com/mypaint/mypaint/blob/v1.2.x/README_LINUX.md

I have installed libmypaint in /usr/local/lib/
and I have exported pkg_config_path: export PKG_CONFIG_PATH=/usr/local/lib//pkgconfig/
But I am still getting the same error.

**Comment by briend** [comment]
@UmarSpa are you building from master branch?  Scons is no longer supported

**Comment by aoloe** [comment]
i could compile mypaint with that change.

but, at the end, when running the resulting mypaint "binary" it cannot find the libmypaint to import.

i gave up and asked if anybody has _correct_ instructions for _compiling_ mypaint outside in the user's home: https://github.com/mypaint/mypaint/issues/949

**Comment by jplloyd** [comment]
Closing this, as #949 is resolved.
