### ISSUE TITLE
Does not build with automake 1.16

### ISSUE THREAD

**Issue by jtojnar** [mypaint/libmypaint#118]
```
I am testing that you have the tools required to build
libmypaint from git. This test is not foolproof.

checking for libtool >= 1.5 ... Major version might be too new (2.4.6)
checking for autoconf >= 2.62 ... yes (version 2.69)
checking for automake >= 1.13 ...
  You must have automake 1.13 or newer installed to compile libmypaint.
  Download the appropriate package for your distribution,
  or get the source tarball at ftp://ftp.gnu.org/pub/gnu/automake/

./autogen.sh: line 152: automake-1.13: not found
Major version might be too new (1.13)
checking for intltool >= 0.40.1 ... yes (version 0.51.0)

Please install/upgrade the missing tools and call me again.
```

**Comment by Jehan** [comment]
Thanks for the report.

It must be fixed now, with the below commit.
Could you just confirm that the build works well until the end with automake 1.16 before I close the bug report?

jehan@DarkMarmot ☃ [libmypaint|master] $ git log --stat
commit 40d9077a80be13942476f164bddfabe842ab2a45 (HEAD -> master, origin/master, origin/HEAD)
Author: Jehan <jehan@girinstud.io>
Date:   Thu Mar 22 13:11:10 2018 +0100

    autogen: adding support of automake 1.16.

 autogen.sh | 3 +++
 1 file changed, 3 insertions(+)

**Comment by jtojnar** [comment]
Works great, thanks.

Downstream commit: https://github.com/NixOS/nixpkgs/commit/43580b680048ca2882f28c806262f803341f5c94
