### ISSUE TITLE
Support for Gegl 0.4.x?

### ISSUE THREAD

**Issue by hartwork** [mypaint/libmypaint#123]
Hi!

Gegl 0.4.0 changes the "application name" from gegl-0.3 to gegl-0.4. As a result, it seems that for Gimp 2.10.0 you need to have both gegl-0.3 and gegl-0.4 installed: Former for libmypaint, latter for GIMP itself.

Are there plans to support or migrate to Gegl 0.4.x in libmypaint? Please note that if some auto-detection is added, Linux distros will need a way to bypass it. Happy to elaborate if needed.

Best, Sebastian

**Comment by hartwork** [comment]
Are there any news on supporting gegl 0.4.x?

**Comment by hartwork** [comment]
@nphilipp made a patch for **Fedora** by now:
https://src.fedoraproject.org/rpms/libmypaint/raw/master/f/libmypaint-1.3.0-gegl04.patch

I made a stripped down version targetting Gegl >=0.4.14 for **Gentoo**:
https://gitweb.gentoo.org/repo/gentoo.git/plain/media-libs/libmypaint/files/libmypaint-1.3.0-gegl-0.4.14.patch?id=8a6496a474e73efa519387bd81a9585820baec58

I can turn the latter into a pull request against branch `libmypaint-v1` if that's welcome.

**Comment by jplloyd** [comment]
gegl-0.4 support added: 059e1993d472a578f2f90e4da906003a636549d4
