### ISSUE TITLE
Unknown Brush Inputs can cause crash

### ISSUE THREAD

**Issue by briend** [mypaint/libmypaint#128]
Basically identical to #74 but for inputs.  This seems to affect only GIMP at the moment, possibly because MyPaint brush.py does some sanitizing?  https://github.com/mypaint/mypaint/blob/master/lib/brush.py#L307-L314

If you add a new input, or rename an input to an invalid value, gimp will crash.  For instance, rename "pressure" to "pressure2"

gimp: mypaint-mapping.c:88: mypaint_mapping_set_n: Assertioninput >= 0 && input < self->inputs' failed.

I opened/closed this bug on GIMP tracker, since libmypaint should handle this better:
https://gitlab.gnome.org/GNOME/gimp/issues/2220

**Comment by briend** [comment]
@Jehan if you could please test this, I'm fairly certain it should prevent GIMP crashing :-D

**Comment by biopsin** [comment]
Thank you and just patched libmypaint 1.3.0
Hm, still crashes just by adding the path  "/usr/share/mypaint-data/2.0/brushes" in Gimp mypaint folders and without even enabling it.

> Warning: Unknown input_id: -1 for input: viewzoom
> Warning: Unknown input_id: -1 for input: viewzoom
> Warning: Unknown setting_id: -1 for setting: gridmap_scale
> Warning: Unknown setting_id: -1 for setting: gridmap_scale_x
> Warning: Unknown setting_id: -1 for setting: gridmap_scale_y
> Warning: Unknown setting_id: -1 for setting: offset_angle
> Warning: Unknown setting_id: -1 for setting: offset_angle_2
> Warning: Unknown setting_id: -1 for setting: offset_angle_2_asc
> Warning: Unknown setting_id: -1 for setting: offset_angle_2_view
> Warning: Unknown setting_id: -1 for setting: offset_angle_adj
> Warning: Unknown setting_id: -1 for setting: offset_angle_asc
> Warning: Unknown setting_id: -1 for setting: offset_angle_view
> Warning: Unknown setting_id: -1 for setting: offset_multiplier
> Warning: Unknown setting_id: -1 for setting: offset_x
> Warning: Unknown setting_id: -1 for setting: offset_y
> Warning: Unknown setting_id: -1 for setting: paint_mode
> Warning: Unknown setting_id: -1 for setting: posterize
> Warning: Unknown setting_id: -1 for setting: posterize_num
> Warning: Unknown setting_id: -1 for setting: smudge_bucket
> Warning: Unknown setting_id: -1 for setting: smudge_length_log
> Warning: Unknown setting_id: -1 for setting: smudge_transparency
> Warning: Unknown input_id: -1 for input: attack_angle
> gimp-2.10: mypaint-mapping.c:89: mypaint_mapping_set_n: Assertion `n >= 0 && n <= 8' failed.
> gimp-2.10: fatal error: Aborted

**Comment by briend** [comment]
I think you should be using the latest 1.x branch:
https://github.com/mypaint/libmypaint/commits/libmypaint-v1
Or, just cherry-pick this commit?
https://github.com/mypaint/libmypaint/commit/0eaae47fc4ecead52e19950e587d7b2a0e615b92

**Comment by Jehan** [comment]
@briend I'll try to make the time to test the coming week. If the crash is confirmed to be fixed, I'd like to propose to make a new (and maybe last) libmypaint 1 release. This bug was most likely the worst problem of the current stable release.

Then you can focus on the future (libmypaint v2). 🙂

**Comment by biopsin** [comment]
Thank you briend, with 749e1da commit did it, Gimp no longer chrashes on adding mypaint-brushes_v2.0 path, the bad input warnings remain, but probably missing the other patches.
I will grab the 1.x when released for packaging.

**Comment by Jehan** [comment]
@biopsin Bad input warnings are probably normal. These brushes use non-supported (in v1) features. The problem was only that libmypaint would crash when such unsupported features were loaded.

**Comment by Jehan** [comment]
@briend Ok so I tested, it's great. It works. It would have been nice if the terminal warnings could also have been naming the brush, but it looks like MyPaintBrush are unnamed (well I can "Comment" and "Description" field in the `myb` files, but it does not look like these are kept around in the struct. Neither is a path or a file name or anything (it looks like libmypaint parse an already extracted string).

Well too bad. Let's say it's good enough for now. At least no crashes, yeah!
