### ISSUE TITLE
How to move the brush (without painting)

### ISSUE THREAD

**Issue by define-private-public** [mypaint/libmypaint#129]
Follow the example here: https://github.com/mypaint/libmypaint/blob/master/examples/minimal.c#L26

I tried adding a second stroke (in the center), like so:

```
// Square
mypaint_surface_begin_atomic((MyPaintSurface *)surface);
stroke_to(brush, (MyPaintSurface *)surface, 0.0, 0.0, 1.0, 0.0);
stroke_to(brush, (MyPaintSurface *)surface, 200.0, 0.0, 1.0, 0.0);
stroke_to(brush, (MyPaintSurface *)surface, 200.0, 200.0, 1.0, 0.0);
stroke_to(brush, (MyPaintSurface *)surface, 0.0, 200.0, 1.0, 0.0);
stroke_to(brush, (MyPaintSurface *)surface, 0.0, 0.0, 1.0, 0.0);
MyPaintRectangle roi;
mypaint_surface_end_atomic((MyPaintSurface *)surface, &roi);

// Line in center
mypaint_surface_begin_atomic((MyPaintSurface *)surface);
stroke_to(brush, (MyPaintSurface *)surface, 100.0, 100.0, 1.0, 0.0);
stroke_to(brush, (MyPaintSurface *)surface, 150.0, 100.0, 1.0, 0.0);
mypaint_surface_end_atomic((MyPaintSurface *)surface, &roi);
```

I'm hoping to get this:
![desired](https://user-images.githubusercontent.com/4551425/46586288-64109880-ca4a-11e8-9cd6-ea260d7cd864.png)

But in reality, I'm getting this:
![render](https://user-images.githubusercontent.com/4551425/46586289-67a41f80-ca4a-11e8-9358-4024c120a632.png)

Is there something else I need to do to get the pen/brush "up"?

**Comment by GGpanda** [comment]
Hello! Can you tell me how to build libmypaint? 
I just failed so many times. Please give me some advice or example.
How to build example?
How to run gegl.py?
How to import gi.respository?
Thank you! :)

**Comment by briend** [comment]
The minimal example has pressure hard coded to 1.0.  I think you could just add that as a parameter to stroke_to and set pressure to 0.0 to effectively lift up the pen.

**Comment by jplloyd** [comment]
I don't think there is a concept of "lifting the brush" in the library. Most brushes will not produce any output when the pressure input is 0, though some do (e.g. the splatter brushes in the Tanda group).

So it depends on what input parameter can be adjusted to produce no output (dabs that are too small or too transparent to render). Most of the time, pressure will be enough. To "lift", create an additional stroke to the same end point, with pressure=0.0, before moving on to the new "starting" point.

There is no need to use additional begin_atomic/end_atomic pairs. They have no impact on this.
