### ISSUE TITLE
Coding error in function fix15_to_rgba8

### ISSUE THREAD

**Issue by chris0e3** [mypaint/libmypaint#133]
Just driving by when I noticed:

File: libmypaint/utils.c, Line: 14
`	fix15_to_rgba8(uint16_t *src, uint8_t *dst, int length)
	...
	      r = *src;
	      g = *src;
	      b = *src;
	      a = *src;
	...
`
should probably be:
`	      r = *src++;
	      g = *src++;
	      b = *src++;
	      a = *src++;
`
Cheers.

**Comment by achadwick** [comment]
I guess this code is unused outside of that PPM stuff. @jonnor any recollection of what/where that stuff was used?

**Comment by jonnor** [comment]
If it is not used in PNG/JPEG export or render to screen in Mypaint then it's probably dead code.
