### ISSUE TITLE
libmypaint 1.4.0 release?

### ISSUE THREAD

**Issue by Jehan** [mypaint/libmypaint#143]
@briend There are quite some nice additions in the libmypaint-v1 branch (new features AND bug fixes). What about we make a libmypaint 1.4.0 release?

After this, you may concentrate on the master branch and leave the older libmypaint code in basic maintenance mode, I think. But at least, let's have a last stable release with all the nice things. :-)

**Comment by Jehan** [comment]
@briend Any way we could get this on the road? I can help. :-)

Basically here is [the release TODO list for GIMP](https://gitlab.gnome.org/GNOME/gimp/blob/master/devel-docs/release-howto.txt). You could get inspired by it and maybe copy part of it.

I'd say the main part for now could be (let's skip the translation things out and you don't need to release any binary builds, I think):

- check README for any issue.
- check version variables in configure.ac
- make a clean repo (either a new clone, or run `git clean -dfx`, but be aware that any file not followed by git will be deleted! So don't do this if you have temp files that you want to keep).
- Run the usual ./autogen.sh && ./configure && make && make check
- Run: `make distcheck` -> this is very important as it creates a tarball for you, then extracts it and runs again a brand new build there automatically; this ensures no files are missing from the tarball.
- Fix any make distcheck bugs, then try again until you get a perfect make distcheck.
- Tag the release (don't forget to push the tag):
```
git tag -s v1.4.0
git push origin v1.4.0
```

- Even though github will create tarballs from you, based on the whole repo, you should also upload the tarballs created by the successful `make distcheck`. These tarballs don't have any irrelevant repository files (like .gitignore or whatever), have a generated configure script (packagers don't care about autogen.sh), and have been tested to be fully working libmypaint builds.

- Update your website, announce the release everywhere, etc.

- Chill out and have whatever you usually drink. 🍾

**Comment by Jehan** [comment]
P.S.: for the record, I just ran a `make distcheck` from a fully cleaned repository and it just works fine. Nothing to fix! Of course, you should also run it and be the one to upload a tag and a tarball as the maintainer.

So I see no problem. I believe we are ready to release as soon as you are (don't forget to edit the configure.ac).

**Comment by Jehan** [comment]
Also as far as I can see, the README looks fine.

**Comment by briend** [comment]
Thank you for the steps @jehan!  I'll seriously try to knock this out by Monday!

**Comment by briend** [comment]
released!  Let's see if I screwed that up! :-)  Thanks again @Jehan

**Comment by Jehan** [comment]
Awesome. I'm making some test builds of GIMP flatpak, which by itself should be a good-enough trial by fire, I guess.

By the way, would be awesome if the mypaint-brushes could also have its release with the same process, for the v1.3.x branch (which may be badly named, as I wonder if the new release should also be 1.4.0 or 1.3.1? Anyway feel free to rename the branch). It may look useless because not much has changed since 1.3.0 release, but there were some minor build system fixes. So it would make a fine 1.3.1 or something.
