### ISSUE TITLE
1.4.0: unable to build gegl duo to build failure via faulty backport

### ISSUE THREAD

**Issue by anthraxx** [mypaint/libmypaint#144]
the faulty commit is the backport in 5e0290c5fb8a175a9f0dd4c6897ff234361c321f
This commit versions the gegl libs, as far as i think, should not have been backported to the 1.x variant.

reverting this commit works flawlessly and keeps the unversioned lib behvior of 1.x

**Comment by Jehan** [comment]
Indeed if we versionned the GEGL lib in the v1 branch, this was a mistake.

I will be computer-less in a few hours (and can't check anything right now) until Tuesday. So this will have to wait next week (or else someone else checks and does what needs to be done). :-)

**Comment by jplloyd** [comment]
Fixed in [1.5.0](https://github.com/mypaint/libmypaint/releases/tag/v1.5.0)
