### ISSUE TITLE
Dealing with seemingly frivolously added languages on Weblate

### ISSUE THREAD

**Issue by jplloyd** [mypaint/libmypaint#146]
## The situation
Translation string updates from Weblate have not been merged for over two years, and the backlog is at 163 changes. 115 of these changes are by the same author, of which 46 are new languages added (more than doubling the old number), all but one with one or (rarely) two subsequent updates by the same author.

Sampling the actual translations, they check out on google translate, but I have to assume that some kind of automatic translation was involved (the individual averaged some ~160 translations per day during a ~3 month period of activity).

Some of the contributions to existing languages are definitely legitimate, though these seem to be limited to fixing missing punctuation (trailing periods, colons, etc.) and similar minor inconsistencies. Relative to the additions and edits of new languages, these are quite few.

Giving **the benefit of the doubt** to the intent of these activities, one could speculate about someone trying to seed encouragement for supporting new translations, but personally I suspect that this was about inflating stats for some reason.

_This individual has also added 41 languages to the mypaint translations in a similar fashion, though I didn't catch it when I merged those changes (lesson learned)._

## The question

What should be done about this? I'm considering:

1. Rebasing all these commits out of existence before merging the other translations into libmypaint.

2. Removing only the commits that add and edit new languages, unless those languages have received subsequent translations by someone else.

As I said, there are legitimate corrections contributed by this person, and none of the translations I've checked seem to be any kind of vandalism, but on the other hand it's
hard to believe that anyone is qualified to provide translations in 50+ languages (there
are also non-punctuation edits to existing languages).

**Comment by Jehan** [comment]
Maybe we could ask this person first if really one is skilled in that many languages. I am personally not against someone contributing for whatever reason (even if for weirdly inflating stats), though it indeed should be meaningful contributions (not robot-translated or badly translated).

Anyway a first step should really be to ask this person about all this.

> This individual has also added 41 languages to the mypaint translations in a similar fashion

Apart from quality, how full are these new languages?

> What should be done about this?

It looks like you may be one who knows the best about this translation process. If so, maybe you should be the one in charge here and making a decision.

@briend do you have any more insight on this topic?

**Comment by jplloyd** [comment]
> though it indeed should be meaningful contributions (not robot-translated or badly translated).

That is my concern, and naturally I cannot verify this myself for most of the languages.

> Anyway a first step should really be to ask this person about all this.

Yeah, I will see if I can contact them.

> Apart from quality, how full are these new languages?

Of the 41:
* 1 is at 90%
* 3 are at ~7%
* The other 37 are between 0.8% and ~3%

This is with fuzzy strings being considered as translated.

At the end of the day it doesn't really matter, but I think it's better if translations are added by people who want to follow through and contribute to them. On the other hand, there is an argument of discoverability for potential contributors who are searching projects based on language in the Weblate interface.

Regardless, we should probably limit the translations we ship based on some threshold, say 90-95% completion.

**Comment by jplloyd** [comment]
I have received no response from the originator. I have squashed the relevant changes into two commits; one that adds the new language files and one with all other changes made by the author (most of which were a few strings added for each new language).

I guess at the end of the day there's no real harm in including the mostly empty language files. Even if the translations are subpar, there are only a few of them for each language. Hopefully their inclusion will lead people who are interested in contributing translations for those languages to find the project via Weblate's project suggestion feature.

**Comment by jplloyd** [comment]
Quick follow-up on this: the contributor informed me that the source of the translations was the DoudouLinux translation project on transifex.

If you have a transifex account, the language groups can be viewed here (after joining the doudoudlinux team for some language).
https://www.transifex.com/jmphilippe/doudoulinux/mypaint/

Based on the number of strings for each language and the activity dates, I think it's probably too outdated to be of use as a source for translations, but at least that means that the "seed strings" in the new languages are likely to be ok.

It should also be noted that the transifex translations predates the weblate setup by at least two years.
