### ISSUE TITLE
Question - Are these patches affective

### ISSUE THREAD

**Issue by libreajans** [mypaint/libmypaint#148]
I tested limypaint.1.3.0, which GIMP use it, with Coverity scan (https://scan.coverity.com/projects/libmypaint-1-3-0-test?tab=overview) and  got 6 warnings about some lines.

These two patches might fix these warnings. 

The first patch: "iterate_over_line_chunks" function's variable order got a warning. Function's order different from its prototype.

The second patch adds free to "self" variable to prevent any leak.

[0001-follow-functions-prototype.patch.txt](https://github.com/mypaint/libmypaint/files/3719342/0001-follow-functions-prototype.patch.txt)

[0001-free-self-to-prevent-leak.patch.txt](https://github.com/mypaint/libmypaint/files/3719343/0001-free-self-to-prevent-leak.patch.txt)

Could you please consider these changes and comment about them.

**Comment by libreajans** [comment]
Also, there is four warning for util.c file.

**Comment by jplloyd** [comment]
Thank you, always good to run these kinds of checks.
In theory both fixes are legitimate, but in practice those functions are essentially example code and the related interfaces are not used by either GIMP or MyPaint.  Regardless, I see no harm in patching them.

**Comment by jplloyd** [comment]
Patches merged: #149 #150
