### ISSUE TITLE
"Change color satur. ({HSV,HSL})" settings on pure greys: switch the hue to red

### ISSUE THREAD

**Issue by achadwick** [mypaint/libmypaint#15]
From mypaint/mypaint#256:

> I'm working on the wet brushes set. They are very interesting to use but I am not capable to resolve the relationship between with the grey values and HSL saturation instances... always the greys are changing the Hue... they appear redish... Perhaps is not possible to do it.
> With other colors works fine my problem is only to modelling de grey tones.
> In this model I'm using basically the Opacity and Color HSL saturation.
> Some suggestion?
> http://pastebin.com/Y7wJjY84 (brush)
> -- @americogobbo

Example:

![weting-proofs-grey-problem](https://cloud.githubusercontent.com/assets/3432543/6629432/e3b47c68-c905-11e4-84a1-c4c3db43cab4.png)

Steps to reproduce:
1. Set "Change color satur. (HSV)" to something > 0
2. Choose `#aaaaaa` or some other pure grey as the colour
3. Paint. Expected grey, actually get a pure-hue red or pink

This is especially noticeable when "Smudge" is high, because then the brush becomes sensitive to what's on the surface.

**Comment by americogobbo** [comment]
@achadwick Do you have an idea if this bug will be fixed on the current devel release - 1.3+?

**Comment by achadwick** [comment]
@americogobbo I hope so, but I don't have time to do this myself for now. Perhaps somebody else could pick it up and see whether it's possible?

**Comment by americogobbo** [comment]
> Perhaps somebody else could pick it up and see whether it's possible?
In previous issue #256 closed we have some commenting by @0ion9 and @iirelu. Perhaps they could help to clarify the bug. 
I am only an artist :-)

**Comment by achadwick** [comment]
The main problem here is that when starting with grey, the HSV or HSL saturation is zero. Grey's hue is undefined really, but it's treated as zero by convention and because we have to put a number on it. The `MYPAINT_BRUSH_SETTING_CHANGE_COLOR_HSV_S` setting is added to the saturation. So adding s=0.2 to a grey like hsv=(0, 0, .3) makes hsv=(0, .2, .3), which is a dark pink. h=0 means reddish tones...

Maybe if the colour saturation and value changer settings were to work as multipliers, _k ∈ [0, 5]_ or something, they might work better? Just adding to 0 sounds wrong for HSV+HSL notions of saturation.

It probably shouldn't be straight linear. Suggestions of function to apply welcome.

Here's the code in question: [mypaint-brush.c:754](https://github.com/mypaint/libmypaint/blob/556c703c08007132c0f5c8de6b1f0fa66e33f127/mypaint-brush.c#L754). It just does addition for the lot. Maybe @martinxyz can shed some light on why this is the way it is?

(Damn, I'm getting involved in it now. I've got an itch to add HCY support to the brush engine and quietly dispose of HSV/HSL.)

**Comment by martinxyz** [comment]
Maybe we can calculate some "hue_definedness" value by multiplying s and v (or something more fancy) and use it to reject saturation changes... something like

`color_s += (color_s*color_v) * settings.change_color_hsv_s;`

which would of course have side-effects... but may be worth testing. (But should we also reject value changes if the hue is ill-defined, or should we assume saturation=0 in this case?)

About "why this is the way it is": it just was easy to implement and it probably pre-dates the "smudge" setting. IIRC it was meant to work always from the user-selected HSV color. But yes, the discontinuity caused by this setting goes against the spirit of brushlib.

Taking a step back, the use-case behind this is probably "fancy brush-defined on-canvas color-mixing". Which maybe could be supported better in other ways...? ( @achadwick there is no hidden reason for using HSV/HSL, except that many people are familiar with it and it's useful to have the choice between controling L vs V depending on the brush. Well, ideally all the mixing and manipulation of picked-up colors would be in some perceptual color space. But anything that breaks the default digital feel of sRGB mixing in a brush-defined way may be worth it.)

**Comment by achadwick** [comment]
Well if the hue is ill-defined because the saturation component is zero, I think it's reasonable to add or subtract a value delta to the grey.

Here's a first attempt at it with what @martinxyz suggested. Looks promising, no weird artefacts:

```diff
diff --git a/mypaint-brush.c b/mypaint-brush.c
index ed54e32..ba07e3a 100644
--- a/mypaint-brush.c
+++ b/mypaint-brush.c
@@ -762,7 +762,7 @@ smallest_angular_difference(float a, float b)
 
     // HSV color change
     color_h += self->settings_value[MYPAINT_BRUSH_SETTING_CHANGE_COLOR_H];
-    color_s += self->settings_value[MYPAINT_BRUSH_SETTING_CHANGE_COLOR_HSV_S];
+    color_s += (color_s * color_v) * self->settings_value[MYPAINT_BRUSH_SETTING_CHANGE_COLOR_HSV_S];
     color_v += self->settings_value[MYPAINT_BRUSH_SETTING_CHANGE_COLOR_V];
 
     // HSL color change
@@ -771,8 +771,8 @@ smallest_angular_difference(float a, float b)
       // this function will CLAMP the inputs
       hsv_to_rgb_float (&color_h, &color_s, &color_v);
       rgb_to_hsl_float (&color_h, &color_s, &color_v);
+      color_s += (color_s * color_v) * self->settings_value[MYPAINT_BRUSH_SETTING_CHANGE_COLOR_HSL_S];
       color_v += self->settings_value[MYPAINT_BRUSH_SETTING_CHANGE_COLOR_L];
-      color_s += self->settings_value[MYPAINT_BRUSH_SETTING_CHANGE_COLOR_HSL_S];
       hsl_to_rgb_float (&color_h, &color_s, &color_v);
       rgb_to_hsv_float (&color_h, &color_s, &color_v);
     }
```

![new saturation variations](https://cloud.githubusercontent.com/assets/61299/25314866/9189690e-2843-11e7-89ac-961ec8f7f98e.png)

**Comment by achadwick** [comment]
However, [note that](https://en.wikipedia.org/wiki/File:Hsl-hsv_models.svg):

![HSV models](https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Hsl-hsv_models.svg/240px-Hsl-hsv_models.svg.png)

* for HSL:
  - Both H and S are ill-defined when either L=0 *or* L=1 (but not in-between)
  - H is ill-defined when S=0 (but L is fine)
* for HSV:
  - Both H and S are ill-defined when V=0 *(only)*
  - H is ill-defined when S=0 (but V is fine)

"Ill-defined" meaning you can set such a variable to anything you like without affecting the resultant colour on your monitor. I'm not a mathematician...

I think I'd prefer to see a term for the minimal absolute distance of L from either 0 or 1 inside the HSL block when we're considering the S change (or an H change?)

And do we need the current numeric value of the variable to be changed to be used? I'm not sure what that buys us.

**Comment by achadwick** [comment]
Okay, so first real attempt to fix this on master now.

![new-satur-fiddles](https://cloud.githubusercontent.com/assets/61299/25316513/8766925e-2860-11e7-85c5-48cd06f45e9e.png)

Let's check to see whether the un-amended V variations are really OK too.

**Comment by achadwick** [comment]
Isolating value alone looks fine. I'm satisfied that it's only the saturation variation settings that need the special casing. Closing, thanks to everyone for helping out :smile: 

![value-twiddles](https://cloud.githubusercontent.com/assets/61299/25317144/8f53d40e-286a-11e7-9dd3-99cb11bd5598.png)
