### ISSUE TITLE
Missing libmypaint v1.4.0 tag

### ISSUE THREAD

**Issue by libreajans** [mypaint/libmypaint#154]
Hi MyPaint team.

While I was trying to build GIMP, I realised there is no v1.4.0 tag and I couldn't directly checkout it.

Would you kindly add a tag for it?

`git checkout v1.4.0`

**Comment by Jehan** [comment]
There is a `v1.4.0` tag. Please see: https://github.com/mypaint/libmypaint/tags

It is one of the commit of the `libmypaint-v1` branch.

If it doesn't work when you `checkout`, it means that you don't have last contents from the repository.

**Comment by libreajans** [comment]
Thanks
