### ISSUE TITLE
Interactive/dynamic brushes [enhancements]

### ISSUE THREAD

**Issue by havocfire** [mypaint/libmypaint#157]
Is it possible to create canvas interactive with brush strokes like this?
 Holding down mouse and going over the canvas produces these strokes.

https://paveldogreat.github.io/WebGL-Fluid-Simulation/
https://github.com/PavelDoGreat/WebGL-Fluid-Simulation

It is very fast and uses GPU.

**Comment by jplloyd** [comment]
Sorry for not responding sooner. In short, this is not possible using only libmypaint (well, theoretically I'm sure you _could,_ but it would be incredibly inefficient). Although there are discussions about adding more simulation-like features in the future, that is currently quite a bit out of scope.
