### ISSUE TITLE
Release 2.0.0 beta version

### ISSUE THREAD

**Issue by avsej** [mypaint/libmypaint#158]
Hi, recently release mypaint 2.0 beta.0 relies on some APIs from master branch.  Could you tag and release libmypaint so that packagers could pick it up?

**Comment by jplloyd** [comment]
v2.0.0-beta.0 is now tagged.

**Comment by jplloyd** [comment]
Alright, I'm currently a bit ill and apparently out of it. No libtool version bump, no release notes etc for that tag, so ignore it. I'll try to make a proper beta release tomorrow unless someone else does it in the meantime.

**Comment by jplloyd** [comment]
Tagged and bagged: https://github.com/mypaint/libmypaint/releases/tag/v2.0.0-beta.1
