### ISSUE TITLE
Scons compilation error

### ISSUE THREAD

**Issue by americogobbo** [mypaint/libmypaint#16]
I'm trying build the libmypaint to enable the MyPaint brushes on the last commit of Gimp Git Master.
During the scons to test only, it appears this error:

jag@jagnome:~/devel/libmypaint$ scons
scons: Reading SConscript files ...
KeyError: 'CPPFLAGS':
  File "/home/jag/devel/libmypaint/SConstruct", line 45:
    env['CCFLAGS'] += SCons.Util.CLVar(os.environ['CPPFLAGS'])
  File "/usr/lib/python2.7/UserDict.py", line 23:
    raise KeyError(key)

The dependencies to scons are OK, because normally I use to build the MyPaint git master every new commit.
My box is ubuntu gnome 14.04.2, i5, 8Gb memory.

**Comment by achadwick** [comment]
@americogobbo Does db27aa0 fix the issue you're seeing?

**Comment by americogobbo** [comment]
Yes, works fine! Thanks!
