### ISSUE TITLE
Tag for 2.0 release

### ISSUE THREAD

**Issue by avsej** [mypaint/libmypaint#164]
I've seen recently mypaint has been released final version of 2.0 series. Is it going to be 2.0 tag for libmypaint?

**Comment by jplloyd** [comment]
No, not for a while. MyPaint 2.0.0 depends on [libmypaint 1.5.0](https://github.com/mypaint/libmypaint/releases/tag/v1.5.0), which backports all that is needed by the 2.0.0 release.
