### ISSUE TITLE
Are all of the "2" structs/functions safe to use?

### ISSUE THREAD

**Issue by define-private-public** [mypaint/libmypaint#168]
Looking at the v1.5.x update, I see things like `MyPaintTiledSurface2` and `mypaint_brush_stroke_to_2()`.  At the moment, are these function and structs considered safe to use?  I'm currently using the vanilla stuff, but I'm also interested in future proofing my application.  Are the originals structs/functions going to be related with the `*2` stuff?

**Comment by jplloyd** [comment]
>
> Safe enough to be used by mypaint 2. Those structs/interfaces make up the
extended interface that backports all new features from the master branch.
See the release notes for 1.5.0 for details on what these features are. The
strokes are also subtly different w. the new interface (and when using it,
the default state for spectral blending is "on", which has to be accounted
for).

As for future proofing, it is unlikely there will be a v1.6.0, and frankly
the answer is "no" regardless.


>

**Comment by jplloyd** [comment]
Not much to add to this. Unless you want to support the new features of the _2 interfaces, there is no need to switch from the old ones.
