### ISSUE TITLE
Dynamic brush with tapers [new feature idea]

### ISSUE THREAD

**Issue by havocfire** [mypaint/libmypaint#176]
Could you implement dynamic brushes like this? 
Open controls, increase the friction value and start moving with mouse as if you're painting. This could be a brush stroke.
https://soulwire.co.uk/muscular-hydrostats/

https://github.com/soulwire/Muscular-Hydrostats

**Comment by odysseywestra** [comment]
This one might be beyond what our bush engine could do but seems like a good idea.

Anyways, could you instead post this feature request on our community fourms? That way this idea can be developed and voted upon so we can see the general interest.

https://community.mypaint.org/c/feature-requests

After you post it, I'll close this issue and we'll re-open it when a contributor decides to tackle this one.

**Comment by odysseywestra** [comment]
https://community.mypaint.org/t/new-dynamic-brushes/2760
