### ISSUE TITLE
how to make it to android?

### ISSUE THREAD

**Issue by pangoo-reuse** [mypaint/libmypaint#183]
what should i do when i build it for android,if you can tell me the build step , thk a lot.
i want use cmake

**Comment by odysseywestra** [comment]
First off this isn't really a support channel so please either go to our Community Forums at https://community.mypaint.org or https://discord.gg/vbB434p and see if you can find appropriate help there. 

Beyond that, this is a Duplicate of #103 . It is something of interest  for some contributors so if you manage to get the library ported to android, you can continue the conversation there.
