### ISSUE TITLE
ImportError: cannot import name _mypaintlib

### ISSUE THREAD

**Issue by smellymoo** [mypaint/libmypaint#187]
on fedora (latest and up to date). I can't run mypaint:

> INFO: mypaint: Installation layout: conventional POSIX-like structure with prefix '/usr'
> Traceback (most recent call last):
>   File "/usr/bin/mypaint", line 293, in <module>
>     = get_paths()
>       ^^^^^^^^^^^
>   File "/usr/bin/mypaint", line 241, in get_paths
>     from lib import fileutils
>   File "/usr/lib64/mypaint/lib/fileutils.py", line 25, in <module>
>     import lib.helpers
>   File "/usr/lib64/mypaint/lib/helpers.py", line 25, in <module>
>     from . import mypaintlib
>   File "/usr/lib64/mypaint/lib/mypaintlib.py", line 13, in <module>
>     from . import _mypaintlib
> ImportError: cannot import name '_mypaintlib' from 'lib' (/usr/lib64/mypaint/lib/__init__.py)

**Comment by smellymoo** [comment]
any help please?

**Comment by katsu-chan** [comment]
Hi! Did you fix that? If you did, how?
