### ISSUE TITLE
Decide versioning for libmypaint: separate from MyPaint, or not?

### ISSUE THREAD

**Issue by achadwick** [mypaint/libmypaint#29]
Once libmypaint has split off from MyPaint properly (mypaint/mypaint#535), should it be given its own distinct version number, or should its version be pegged to MyPaint's version?

**Comment by Jehan** [comment]
I guess it all depends if one project becomes much faster than the other. In particular if libmypaint becomes so used in third-party projects that it gets bug fixes faster than MyPaint itself is released, it may then be wised to release a version of libmypaint separately.

This said, libmypaint can start as following MyPaint's version and if the need arises some day, then you can always split later. Or you can split already now and make the separation as clean as possible.

I know: my answer is not helpful. :-P

**Comment by hartwork** [comment]
Since Gimp is checking for libmypaint >=1.1 current, please don't start at something below like 0.8 or so. If that's out of discussion anyway, please excuse the noise.

**Comment by odysseywestra** [comment]
I would vote starting off with same version as MyPaint currently is and
keep it version number in line with MyPaint to avoid confusion.

On Wed, Dec 23, 2015, 3:10 PM Sebastian Pipping <notifications@github.com>
wrote:

> Since Gimp is checking for libmypaint >=1.1 current, please don't start at
> something below like 0.8 or so. If that's out of discussion anyway, please
> excuse the noise.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mypaint/libmypaint/issues/29#issuecomment-167006613>.
>
-- 

-- Albert Westra

**Comment by achadwick** [comment]
@hartwork Existing/deployed .pc files matter, so we won't go before those. Currently you'll get 1.1 in those.

Noting that even huge projects like GNOME basically even peg app versions to the main version number. It can be done. Let's do as @odysseywestra suggests initially, and bump libmypaint's .pc version forward to 1.2.0 at the upcoming MyPaint release so that GIMP can be sure it's getting the latest translations at least. When libmypaint goes independent (probably at 1.2.1), we'll start bumping both together and see what happens.

**Comment by Jehan** [comment]
I doubt down-versioning was ever an alternative for upstream so I didn't even mention it. In case it was not, of course any split version number should continue after the current shared version.

**Comment by achadwick** [comment]
Oh, drat. I didn't bump brushlib_version for the MyPaint release as I said I would. That will have to change for the first release, in that case.  Anyway, time to review milestones and suchlike.

libmypaint is now sharedlib-by-default, so we could call what we have v1.2.0 since it's basically what MyPaint v1.2.0 is using. Let's create a formal v1.2.0 release tag soon.

I would like to use Semantic Versioning for libmypaint: http://semver.org/, similar to MyPaint. I am happy for the versions to start drifting right away.

**Comment by Jehan** [comment]
Awesome. Speaking of drifting version, would it be possible to review https://github.com/mypaint/mypaint/pull/538 which would create a data package (which could itself have its own drifting versionning)?
This would be a big deal for GIMP.

**Comment by achadwick** [comment]
"Soon"... ahem, whoops. I got sidetracked by the MyPaint release and real life. Need to re-focus on this and make a decision.

I think MyPaint 1.3.0 will be the first to use the independent libmypaint, so maybe our initial independent release of libmypaint should match that version. Thinking about it again, it would be nice for us to avoid confusion while were doing the split. We can decide whether to let versions drift or keep them in step afterwards.

MyPaint has a `v1.2.x` branch for the 1.2.1 release and any little bugfix releases beyond that point. It uses SCons and the submodule trick, and it can remain pinned to a specific historic libmypaint revision without any trouble.

**Comment by achadwick** [comment]
Milestone renamed <https://github.com/mypaint/libmypaint/milestones/v1.3.0>, and we have a plan now.
