### ISSUE TITLE
Mac OSX gegl Error

### ISSUE THREAD

**Issue by Partha1b** [mypaint/libmypaint#33]
I am getting the following error:

```
gegl/mypaint-gegl-surface.c:29:3: error: redefinition of typedef 'MyPaintGeglTiledSurface' is a C11 feature [-Werror,-Wtypedef-redefinition]
} MyPaintGeglTiledSurface;
  ^
gegl/mypaint-gegl-surface.h:27:41: note: previous definition is here
typedef struct _MyPaintGeglTiledSurface MyPaintGeglTiledSurface;
                                        ^
1 error generated.
scons: *** [gegl/mypaint-gegl-surface.os] Error 1
scons: building terminated because of errors.
```

**Comment by achadwick** [comment]
@Partha1b thanks for reporting. What revision of libmypaint is this? Please paste the long hexadecimal string at the top of `git log` into this bug report.

**Comment by Partha1b** [comment]
I think this is what you are asking?
0000000000000000000000000000000000000000 0c1ae4aa179c48d6d7bffdb9b7215f1620827ab3

**Comment by su-v** [comment]
Just for the record:
On OS X 10.7.5, with clang from Xcode 4.6.3, I get (several) warnings (```[-Wtypedef-redefinition]```) instead of (fatal) errors about such issues (libmypaint 0c1ae4aa179c48d6d7bffdb9b7215f1620827ab3) - the warnings ofc don't cause the build to fail (they are also present when compiling GIMP git master).
```
$ clang --version
Apple LLVM version 4.2 (clang-425.0.28) (based on LLVM 3.2svn)
Target: x86_64-apple-darwin11.4.2
Thread model: posix
```

Note also that on OS X 10.7.5 using the legacy compiler from Xcode 4.6.3 (```llvm-gcc-4.2```) does indeed fail to compile recent checkouts of libmypaint due to the same issue (if libmypaint is installed with ```enable_gegl=true```). With that compiler, GIMP git master builds likely fails independent of how libmypaint itself was configured (I stopped using that compiler for one the GIMP git master builds after the initial failure).
```
$ llvm-gcc-4.2 --version
i686-apple-darwin11-llvm-gcc-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)
Copyright (C) 2007 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Whatever solution will be chosen to solve these warnings - please keep in mind that if you choose to require C++11 (to silence the warnings), this will drop support for future MyPaint 1.2 (along with GIMP git master) on older OS X versions which default to ```libstdc++``` (<= 10.8) along with the system compilers provided by Apple.

**Comment by su-v** [comment]
All warnings when installing MyPaint from git master (libmypaint configured with ```enable_gegl=true```), using clang from Xcode 4.6.3 (installed glib version is 2.46.2):
```
In file included from brushlib/gegl/mypaint-gegl-surface.c:20:
In file included from brushlib/gegl/mypaint-gegl-surface.h:25:
In file included from brushlib/mypaint-tiled-surface.h:5:
In file included from brushlib/mypaint-surface.h:21:
brushlib/mypaint-glib-compat.h:26:16: warning: redefinition of typedef 'gpointer' is a C11 feature [-Wtypedef-redefinition]
typedef void * gpointer;
               ^
/Volumes/magenta/mp-trunk/x11/include/glib-2.0/glib/gtypes.h:77:15: note: previous definition is here
typedef void* gpointer;
              ^
In file included from brushlib/gegl/mypaint-gegl-surface.c:20:
In file included from brushlib/gegl/mypaint-gegl-surface.h:25:
In file included from brushlib/mypaint-tiled-surface.h:5:
In file included from brushlib/mypaint-surface.h:21:
brushlib/mypaint-glib-compat.h:29:14: warning: redefinition of typedef 'gchar' is a C11 feature [-Wtypedef-redefinition]
typedef char gchar;
             ^
/Volumes/magenta/mp-trunk/x11/include/glib-2.0/glib/gtypes.h:46:16: note: previous definition is here
typedef char   gchar;
               ^
In file included from brushlib/gegl/mypaint-gegl-surface.c:20:
In file included from brushlib/gegl/mypaint-gegl-surface.h:25:
In file included from brushlib/mypaint-tiled-surface.h:5:
In file included from brushlib/mypaint-surface.h:21:
brushlib/mypaint-glib-compat.h:30:13: warning: redefinition of typedef 'gint' is a C11 feature [-Wtypedef-redefinition]
typedef int gint;
            ^
/Volumes/magenta/mp-trunk/x11/include/glib-2.0/glib/gtypes.h:49:16: note: previous definition is here
typedef int    gint;
               ^
In file included from brushlib/gegl/mypaint-gegl-surface.c:20:
In file included from brushlib/gegl/mypaint-gegl-surface.h:25:
In file included from brushlib/mypaint-tiled-surface.h:5:
In file included from brushlib/mypaint-surface.h:21:
brushlib/mypaint-glib-compat.h:31:14: warning: redefinition of typedef 'gboolean' is a C11 feature [-Wtypedef-redefinition]
typedef gint gboolean;
             ^
/Volumes/magenta/mp-trunk/x11/include/glib-2.0/glib/gtypes.h:50:16: note: previous definition is here
typedef gint   gboolean;
               ^
In file included from brushlib/gegl/mypaint-gegl-surface.c:20:
In file included from brushlib/gegl/mypaint-gegl-surface.h:25:
In file included from brushlib/mypaint-tiled-surface.h:5:
In file included from brushlib/mypaint-surface.h:21:
brushlib/mypaint-glib-compat.h:34:24: warning: redefinition of typedef 'guint16' is a C11 feature [-Wtypedef-redefinition]
typedef unsigned short guint16;
                       ^
/Volumes/magenta/mp-trunk/x11/lib/glib-2.0/include/glibconfig.h:40:24: note: previous definition is here
typedef unsigned short guint16;
                       ^
brushlib/gegl/mypaint-gegl-surface.c:29:3: warning: redefinition of typedef 'MyPaintGeglTiledSurface' is a C11 feature [-Wtypedef-redefinition]
} MyPaintGeglTiledSurface;
  ^
brushlib/gegl/mypaint-gegl-surface.h:27:41: note: previous definition is here
typedef struct _MyPaintGeglTiledSurface MyPaintGeglTiledSurface;
                                        ^
6 warnings generated.



In file included from brushlib/tests/gegl/test-gegl-surface.c:4:
In file included from brushlib/gegl/mypaint-gegl-surface.h:25:
In file included from brushlib/mypaint-tiled-surface.h:5:
In file included from brushlib/mypaint-surface.h:21:
brushlib/mypaint-glib-compat.h:26:16: warning: redefinition of typedef 'gpointer' is a C11 feature [-Wtypedef-redefinition]
typedef void * gpointer;
               ^
/Volumes/magenta/mp-trunk/x11/include/glib-2.0/glib/gtypes.h:77:15: note: previous definition is here
typedef void* gpointer;
              ^
In file included from brushlib/tests/gegl/test-gegl-surface.c:4:
In file included from brushlib/gegl/mypaint-gegl-surface.h:25:
In file included from brushlib/mypaint-tiled-surface.h:5:
In file included from brushlib/mypaint-surface.h:21:
brushlib/mypaint-glib-compat.h:29:14: warning: redefinition of typedef 'gchar' is a C11 feature [-Wtypedef-redefinition]
typedef char gchar;
             ^
/Volumes/magenta/mp-trunk/x11/include/glib-2.0/glib/gtypes.h:46:16: note: previous definition is here
typedef char   gchar;
               ^
In file included from brushlib/tests/gegl/test-gegl-surface.c:4:
In file included from brushlib/gegl/mypaint-gegl-surface.h:25:
In file included from brushlib/mypaint-tiled-surface.h:5:
In file included from brushlib/mypaint-surface.h:21:
brushlib/mypaint-glib-compat.h:30:13: warning: redefinition of typedef 'gint' is a C11 feature [-Wtypedef-redefinition]
typedef int gint;
            ^
/Volumes/magenta/mp-trunk/x11/include/glib-2.0/glib/gtypes.h:49:16: note: previous definition is here
typedef int    gint;
               ^
In file included from brushlib/tests/gegl/test-gegl-surface.c:4:
In file included from brushlib/gegl/mypaint-gegl-surface.h:25:
In file included from brushlib/mypaint-tiled-surface.h:5:
In file included from brushlib/mypaint-surface.h:21:
brushlib/mypaint-glib-compat.h:31:14: warning: redefinition of typedef 'gboolean' is a C11 feature [-Wtypedef-redefinition]
typedef gint gboolean;
             ^
/Volumes/magenta/mp-trunk/x11/include/glib-2.0/glib/gtypes.h:50:16: note: previous definition is here
typedef gint   gboolean;
               ^
In file included from brushlib/tests/gegl/test-gegl-surface.c:4:
In file included from brushlib/gegl/mypaint-gegl-surface.h:25:
In file included from brushlib/mypaint-tiled-surface.h:5:
In file included from brushlib/mypaint-surface.h:21:
brushlib/mypaint-glib-compat.h:34:24: warning: redefinition of typedef 'guint16' is a C11 feature [-Wtypedef-redefinition]
typedef unsigned short guint16;
                       ^
/Volumes/magenta/mp-trunk/x11/lib/glib-2.0/include/glibconfig.h:40:24: note: previous definition is here
typedef unsigned short guint16;
                       ^
5 warnings generated.
```

**Comment by su-v** [comment]
Similar [compiler warnings](https://gist.github.com/su-v/b6ca5c948ebbc6c3e08f) from latest GIMP git master (also on OS X 10.7.5).

**Comment by Partha1b** [comment]
For me, it was not an error but compiling was terminated as I showed above.

In case, my Mac version etc. is required ...

clang --version
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.2.0
Thread model: posix

I am using El Capitan.

As an aside, I enabled il8n and scon cannot locate by libintl.h file. How do I modify the Sconscript so that it can locate my header files?

PS: I don't have compiler warnings with GIMP as of my last build other than pthread.

**Comment by su-v** [comment]
su-v commented earlier:
> (…) to require C++11 (…), this will drop support for future MyPaint 1.2 (along with GIMP git master) on older OS X versions

Feel free to ignore - I'm aware that e.g. current stable glibmm and gtkmm3 already switched to c++11 (required).

**Comment by Partha1b** [comment]
I seem to have been able to build libmypaint:
Modified SConstructs (line 69 on):
#env.Append(CXXFLAGS=' -Wall -Wno-sign-compare -Wno-write-strings')
#env.Append(CCFLAGS='-Wall -Wstrict-prototypes -Werror')
#env.Append(CFLAGS='-std=c99')
env.Append(CFLAGS=' -I/Users/partha/local/include -O3 -ffast-math -ftree-vectorize -mmacosx-version-min=10.8')
env.Append(LDLAGS=' -headerpad_max_install_names -L/Users/partha/local/lib')

(The last 2 lines are specific to my build and I commented out the others.

I modified mypaint-fixed-tiled-surface.c (Line 116)
/*        fprintf(stderr, "CRITICAL: unable to allocate enough memory: %Zu bytes", buffer_size);*/
        fprintf(stderr, "CRITICAL: unable to allocate enough memory: %lu bytes", buffer_size);
%Z gives an error.

Finally:
scons -c
scons enable_gegl=True use_sharedlib=yes use_glib=yes enable_i18n=True prefix=/tmp/gimp2.9series/McGimp-2.9.app/Contents/Resources/ install

**Comment by achadwick** [comment]
@Partha1b are you asking us to change libmypaint here, or telling us that you got MyPaint to compile and that it's OK to close this issue? Let me know what you want us to do.

I don't want to drop the `-Wall`, and I don't want to drop the `-std=c99` which introduces `%z<integer-spec>`. The line in the code should probably be changed to `%zu` though:

> ‘z’ was introduced in ISO C99. ‘Z’ is a GNU extension predating this addition and should not be used in new code.
-- https://www.gnu.org/software/libc/manual/html_node/Integer-Conversions.html

**Comment by Partha1b** [comment]
@achadwick, I was reporting that I could compile libmypaint. I will try again with -Wall and -std=c99 to see if it compiles. If not, I will have to continue modifying at my end since this has become a requirement for GIMP and so I cannot compile GIMP without libmypaint.

I guess we can close the issue if you are planning to modify mypaint-fixed-tiled-surface.c?

**Comment by achadwick** [comment]
@Partha1b can you re-test and let me know if @lantw44 's recent changes fix your build? Thanks.

**Comment by Partha1b** [comment]
Hi,

Yes, my builds are now fixed. Thanks very much.

Partha
