### ISSUE TITLE
Anybody could tell me what's problem of my application?

### ISSUE THREAD

**Issue by loveq369** [mypaint/libmypaint#39]
I have write a small application. But I have some bug. I use "calligraphy.myb". What's the problem? Could anybody tell me?

![snip20160111_1](https://cloud.githubusercontent.com/assets/5432020/12233648/7edb329e-b8a3-11e5-89c7-c0d92548f8f2.png)

**Comment by achadwick** [comment]
I haven't the foggiest idea. I simply can't tell based on this report, and I'm not certain this is actually a libmypaint issue either.

* What version of libmypaint are you using?
* How is it configured?
* Please link to the source code you are developing.
* Is this FOSS software?

Looks a little like an alpha channel problem, but I don't know what your pixel buffers are like.

TRIAGE: really sounds like user support to me, and I don't think the issue tracker is the correct place for this discussion. <http://community.mypaint.org> might be a better venue? IMO, we should close this issue after two weeks if we're getting nowhere.
