### ISSUE TITLE
LD_LIBRARY_PATH is ignored when running g-ir-scanner

### ISSUE THREAD

**Issue by lantw44** [mypaint/libmypaint#40]
In file `SConscript`, function `add_gobject_introspection`:
```
scanner_cmd = """LD_LIBRARY_PATH=./ g-ir-scanner -o $TARGET --warn-all \    
    --namespace=%(gi_name)s --nsversion=%(version)s --add-include-path=./ \ 
    --identifier-prefix=%(type_prefix)s --symbol-prefix=%(func_prefix)s \   
    %(pkgs)s %(includeflags)s %(gi_includes)s \
    --library=%(libname)s $SOURCES""" % locals()
```

This ignores the value of LD_LIBRARY_PATH set by the user. If GEGL is installed in a directory that cannot be found without setting LD_LIBRARY_PATH, g-ir-scanner will fail because required shared libraries cannot be found.

**Comment by achadwick** [comment]
Does doing the obvious `scanner_cmd = """LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH g-ir-scanner […]` hack fix it? It may well not if SCons imposes its own environ.

**Comment by lantw44** [comment]
No, it expands to an empty string.
```
LD_LIBRARY_PATH=./: g-ir-scanner -o MyPaintGegl-1.1.gir --warn-all --namespace=MyPaintGegl --nsversion=1.1 --add-include-path=./ --identifier-prefix=MyPaintGegl --symbol-prefix=mypaint_gegl --pkg=glib-2.0 --pkg=gegl-0.3 -I./ -I./gegl --include=Gegl-0.3 --include=MyPaint-1.1 --library=mypaint-gegl gegl/mypaint-gegl-surface.c gegl/mypaint-gegl-surface.h glib/mypaint-gegl-glib.c glib/mypaint-gegl-glib.h
printf: write error on stdout
```

**Comment by achadwick** [comment]
Okay, was worth a shot. This will need either a new SCons variable setting up, or some extra code to propagate `LD_LIBRARY_PATH` to `g-ir-scanner`. The "natural" place to add that would be at [SConstruct:45](https://github.com/mypaint/libmypaint/blob/6f482bd6fdc462bb06df15a157edee7035b3ccf9/SConstruct#L45).

**Comment by lantw44** [comment]
This simple fix works for me:
```diff
diff --git a/SConscript b/SConscript
index f033c39..7675460 100644
--- a/SConscript
+++ b/SConscript
@@ -22,7 +22,7 @@ def add_gobject_introspection(env, gi_name, version,
     includeflags = ' '.join(['-I%s' % s for s in includepaths])
     gi_includes = ' '.join(['--include=%s' % s for s in includes])
 
-    scanner_cmd = """LD_LIBRARY_PATH=./ g-ir-scanner -o $TARGET --warn-all \
+    scanner_cmd = """LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH g-ir-scanner -o $TARGET --warn-all \
         --namespace=%(gi_name)s --nsversion=%(version)s --add-include-path=./ \
         --identifier-prefix=%(type_prefix)s --symbol-prefix=%(func_prefix)s \
         %(pkgs)s %(includeflags)s %(gi_includes)s \
diff --git a/SConstruct b/SConstruct
index ad1452a..7e88cdf 100644
--- a/SConstruct
+++ b/SConstruct
@@ -54,6 +54,8 @@ if os.environ.has_key('CPPFLAGS'):
 if os.environ.has_key('LDFLAGS'):
     # LDFLAGS is omitted in SHLINKFLAGS, which is derived from LINKFLAGS
    env['LINKFLAGS'] += SCons.Util.CLVar(os.environ['LDFLAGS'])
+if os.environ.has_key('LD_LIBRARY_PATH'):
+   env['LD_LIBRARY_PATH'] = SCons.Util.CLVar(os.environ['LD_LIBRARY_PATH'])
 
 opts.Update(env)
 ```

**Comment by achadwick** [comment]
Gegl will not be part of the default libmypaint configuration for its formal 1.2.0 release because GIMP does not require it.

However this fix would be nice to have in v1.2.0 for people building different configs. Thanks!

**Comment by achadwick** [comment]
@lantw44 libmypaint has just gone autotools. Can you confirm that this problem is absent now?

(And the upcoming version number has changed... ☺)

**Comment by lantw44** [comment]
It is nice to see the move to autotools. It builds without problems now.
