### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [mypaint/libmypaint#45]
I would like to point out that identifiers like "[`_MyPaintSurface`](https://github.com/mypaint/libmypaint/blob/207d21ff41e4842a1f4e0f4f5e19c1dd995a9250/mypaint-surface.h#L26)" and "[`_OperationQueue`](https://github.com/mypaint/libmypaint/blob/207d21ff41e4842a1f4e0f4f5e19c1dd995a9250/operationqueue.h#L24)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by odysseywestra** [comment]
@elfring if you want, you can fork it and fix the identifiers and send us a pull request with the fix. That would be a great help.

**Comment by elfring** [comment]
Will a renaming of such identifiers affect also [the application binary interface](https://en.wikipedia.org/wiki/Application_binary_interface "Description around application binary interface usage") for this software?

**Comment by achadwick** [comment]
libmypaint is written in C, and loosely conforms to the C99 standard. Why are you asking for this?

**Comment by achadwick** [comment]
@elfring 
We'll have to consider API consistency more carefully than we do in future. ABI consistency is less important IMO.

A bit more context would help us understand the issue you are having. What problems is this naming causing you? 

Otherwise, for now, I'm not sure if this is an issue we need to fix, frankly.

**Comment by elfring** [comment]
>Why are you asking for this?

I imagine that more software release planning would be needed if you care for API/ABI stability around affected identifiers.


>What problems is this naming causing you?

How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by achadwick** [comment]
Hit me with practical suggestions about how we can improve things, tell me what's actually going wrong, or (better still) make PRs to fix dud behaviour please.

We can also consider automated tools as suggested in #46.

**Comment by achadwick** [comment]
Still no practical suggestions or error messages from the reporter. Our codebase seems to be merely doing this to avoid confusing `struct Foo` and `Foo` types though, which is silly.

Picking this up for the release for another look. There are structures which probably should go private just for the sake of cleaning up the interface.

@elfring Tell me what problems this is causing you, or give me a concrete way of testing this. Compiler error messages, test cases, anything. Better still, send a PR.

**Comment by elfring** [comment]
Would you really like to "test" [undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?   ;-)

**Comment by achadwick** [comment]
@elfring Yes please. Suggestions for linters, compiler flags, or similar checks.

**Comment by elfring** [comment]
* Would you like to try an ordinary source code search out again?
* How do you think about to [achieve improvements in the affected software application domain](https://developerblog.redhat.com/2014/10/16/gcc-undefined-behavior-sanitizer-ubsan/ "GCC Undefined Behavior Sanitizer")?

**Comment by achadwick** [comment]
As if I haven't already, you mean? I think you'll find that making a 

Thanks for the link to the [ubsan information on the RedHat blog](https://developerblog.redhat.com/2014/10/16/gcc-undefined-behavior-sanitizer-ubsan/). Looks as if it could be useful, but I note one of the comments on the post:

> Most GNOME projects are maintained or contributed to by Red Hat and the use of reserved identifiers is pervasive among those projects. By pervasive, I mean close to 100% of GNOME projects do it and many of the examples in the documentation do too. It’s almost like some kind of style guide there.

Dunno if our use of GLib or GI will be a problem there.

**Comment by elfring** [comment]
Thanks for [your source code improvement](https://github.com/mypaint/libmypaint/commit/4b1d19574c011f08ab0f1c9c77226998af86ede5 "Deletion of some underscores").
