### ISSUE TITLE
brush engine not aware of canvas rotation

### ISSUE THREAD

**Issue by briend** [mypaint/libmypaint#67]
I've been working on some pretty complex brushes, and I finally tried them out while rotating the canvas.  I noticed all the direction information is kept oriented with the original position.  It's as if the canvas has not rotated and only the view of the canvas has rotated.  If your brush is affected by X/Y offsets, Ascension, direction, barrel-rotation, etc, it won't behave as you might expect-- suddenly your pen is upside down or the thick/thin angle gets flipped around, etc.  This is related to issue #66, and I think view-rotation (degrees) will need to be added as an input in addition to the zoom-level.  I've had some success adding barrel-rotation so I think I'll take a stab at adding both of these as inputs and applying them to offset the affected inputs-- hopefully it's as easy as just adding the zoom-rotation degrees the current input value.

**Comment by briend** [comment]
This seems like an continuation of [this bug/](https://gna.org/bugs/?19988)conversation a few years ago.  So the tilt is being corrected in freehand.py before being sent over to brush engine.  I don't think there is any way to correct this in freehand.py, we really do need to send tdw.rotation over to brush engine.  Is there any performance issue with adding more data?  I'm adding barrel-rotation, and now probably zoom and tdw.rotation to the data model. . .

line 558 in freehand.py
        # Tilt inputs are assumed to be relative to the viewport,
        # but the canvas may be rotated or mirrored, or both.
        # Compensate before passing them to the brush engine.
        # https://gna.org/bugs/?19988
        if tdw.mirrored:
            xtilt *= -1.0
        if tdw.rotation != 0:
            tilt_angle = math.atan2(ytilt, xtilt) - tdw.rotation
            tilt_magnitude = math.sqrt((xtilt**2) + (ytilt**2))
            xtilt = tilt_magnitude * math.cos(tilt_angle)
            ytilt = tilt_magnitude * math.sin(tilt_angle)

**Comment by achadwick** [comment]
IMO this is acceptable right now, and keeps the view independent of the model. Demonstrate any actual discontinuities and prepare a patch, and I'll re-open.

What is barrel rotation exactly? Rotation of the pen around the axis of tilt?

**Comment by briend** [comment]
Barrel rotation is Gdk.AxisUse.WHEEL, but yeah basically twisting the pen on it's tilt axis. I've updated https://github.com/mypaint/mypaint/issues/26 with links to my branches that add this input.  Below is a quick screenshot of some issues-- each quadrant represents the view at 0, 90, 180, and -90 rotations.  I've noted in red what is wrong.  Sometimes the brush should be the same, other times the brush should change.  The first two inputs are standard, the 3rd is Anti-art's Y offset, and the next is barrel rotation which has to be corrected with ascension (the raw rotation input varies with ascension).  Anti-Art's Dir360 is the last one, also affected. 
![mypaint-view-rotation-issues](https://cloud.githubusercontent.com/assets/6015639/17652548/cc385834-6233-11e6-8648-bf0d3dc581c4.jpg)

I'll be taking a stab at a patch soon.  Thanks Andrew!

**Comment by briend** [comment]
Hi Andrew, I've made some progress on a branch to correct for rotation and zoom-- 
https://github.com/briend/libmypaint/tree/view-zoom
and
https://github.com/briend/mypaint/tree/view-zoom

So far I've got Direction and Ascension corrected for view-rotation.  Only freehand works right now but it is enough to see a big difference, particularly with Direction dynamics.  Check out a quick video I put on youtube:  https://youtu.be/2us8VB3OAfU

Thanks for looking.  I'm really excited about this because some of the brushes I'm working on get totally messed up when rotating the view, which is really handy when trying to get good strokes like the way animators spin their animator discs.

**Comment by briend** [comment]
@achadwick the two forks now work for all the drawing tools (yay).  I'm really happy.  I also have zoom-correction working for speed which I will update in the other issue thread with a demo video.  Thanks! :-D

**Comment by briend** [comment]
Started a community discussion here:
https://community.mypaint.org/t/zoom-and-view-rotation-corrections-rfc/465

**Comment by briend** [comment]
This issue can stay closed I think it is redundant and really just one big calibration project
