### ISSUE TITLE
Redundant division done in performance-sensitive areas

### ISSUE THREAD

**Issue by iirelu** [mypaint/libmypaint#73]
There's a bunch of code in [brushmodes.c](https://github.com/mypaint/libmypaint/blob/master/brushmodes.c) that looks like `x / (1<<15)`. This is a weird calculation to do, as it doesn't need division. As far as I can tell, `x >> 15` is identical.

If gcc isn't optimising `/ (1<<15)` to `>>15`, this is a significant performance hit as divisions are a lot more costly than bitshifts.

**Comment by briend** [comment]
I don't think this is worth worrying about, and we should really look forward to scene-referred floating point, so no divisions needed at all.
