### ISSUE TITLE
viewrotation is not listed in brushsettings.json

### ISSUE THREAD

**Issue by achadwick** [mypaint/libmypaint#89]
After integrating PR #70, I noticed that the View Rotation input is not listed in brushsettings.json, meaning that MyPaint cannot see it or create brushes which depend on it. It is however listed as a state.

Should it be added as an input too? MyPaint code now feeds it through into libmypaint.

Related: mypaint/mypaint#817.

**Comment by briend** [comment]
Originally zoom and viewrotation were just meant to calibrate the other inputs.  I added zoom as an input just as a bonus, but I couldn't think of a good reason to have viewrotation an actual brush input.  That said there is no reason it couldn't be an input :)

**Comment by achadwick** [comment]
Okay, that's reasonable given what it seems to be doing. I've done the obvious "does it break my tilt brush" test, and it doesn't seem to be doing that. Thanks for the explanation ☺
