### ISSUE TITLE
Expand our CI Tools Build Test Configuations

### ISSUE THREAD

**Issue by odysseywestra** [mypaint/libmypaint#98]
After we address #97, we should add various build configurations tests as well to avoid any commits or pull requests that may potentially break the building process. I'll probably work on this one when it comes time to. In the meantime what build config options should we test out? The obvious first choice should be `--gegl-enabled` option.

**Comment by jtojnar** [comment]
Weirdly, there should have been CI for those variants at the time of opening this issue:

https://github.com/mypaint/libmypaint/commit/7e522a5540d6676cd0eb127ba26bdb16f1ad7d43
https://github.com/mypaint/libmypaint/commit/8d81a62a61cab5654d7fa85db1328ab6f33d1f1c

We no longer use Travis but the matrix got ported to GitHub actions:

https://github.com/mypaint/libmypaint/commit/461cf8d6cd0550cd32f5c2a1234f077c67765008
